import 'package:axlpl_delivery/app/data/localstorage/local_storage.dart';
import 'package:axlpl_delivery/common_widget/awsome_notification.dart';
import 'package:axlpl_delivery/utils/utils.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';
import 'package:google_fonts/google_fonts.dart';
import 'app/routes/app_pages.dart';

// core Flutter primitives
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  NotificationService.showNotification(
      message); // 🔥 trigger local notification
}

final LocalStorage _localStorage = LocalStorage();

// generated by
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  await NotificationService.init();

  // await Firebase.initializeApp();
  final messaging = FirebaseMessaging.instance;
  NotificationSettings settings = await messaging.requestPermission(
    alert: true,
    announcement: false,
    badge: true,
    carPlay: false,
    criticalAlert: false,
    provisional: false,
    sound: true,
  );

  if (kDebugMode) {
    print('Permission granted: ${settings.authorizationStatus}');
  }
  String? token = await messaging.getToken();
  Utils().log(token);

  await storage.write(key: _localStorage.fcmToken, value: token);

  // OneSignal.Debug.setLogLevel(OSLogLevel.verbose);
  // OneSignal.initialize("ff262d3f-067a-4c80-a370-08f18ed8b4c2");
  // OneSignal.Notifications.requestPermission(false);

  runApp(
    ScreenUtilInit(
      designSize: ScreenUtil.defaultSize,
      child: GetMaterialApp(
        enableLog: true,
        defaultTransition: Transition.fadeIn,
        title: "AXLPL Delivery",
        // builder: (context, child) {
        //   ErrorWidget.builder = (FlutterErrorDetails details) {
        //     return ErrorScreen(); //
        //   };

        //   return child!;
        // },
        initialRoute: AppPages.INITIAL,
        getPages: AppPages.routes,
        theme: ThemeData(textTheme: GoogleFonts.workSansTextTheme()),
      ),
    ),
  );
}
